[package]
name = "jughisto"
version = "0.1.0"
authors = ["fer22f <3057302+fer22f@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
diesel = { version = "1.4.5", features = ["sqlite"] }
rocket_contrib = { version = "0.4.5", default-features = false, features = ["json", "serve", "diesel_sqlite_pool", "uuid", "handlebars_templates"] }
serde = { version = "1.0.116", features = ["derive"] }
dotenv = "0.15.0"
rust-argon2 = "0.8"
zip = "0.5"
thiserror = "1.0"
quick-xml = { version = "0.19.0", features = ["serialize"] }
regex = "1"
which = "4.0.2"
serde_json = "1.0"
