version: "3.1"

services:
  jughisto:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
      - "50051:50051"
    env_file:
      - .dev_env
    volumes:
      - ".:/usr/src/jughisto"
      - "cargo_registry:/usr/local/cargo/registry"
      - "cargo_git:/usr/local/cargo/git"
      - "./data:/data"
  alvokanto:
    build:
      context: .
      dockerfile: alvokanto/dev.Dockerfile
    volumes:
      - ".:/usr/src/jughisto"
      - "cargo_registry:/usr/local/cargo/registry"
      - "cargo_git:/usr/local/cargo/git"
      - "./data:/data"

volumes:
  cargo_registry:
  cargo_git:
