version: "3.1"

services:
  jughisto:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "50051"
  alvokanto:
    depends_on:
      - jughisto
    build:
      context: .
      dockerfile: alvokanto/Dockerfile
    privileged: true
