version: "3.1"

services:
  jughisto:
    ports:
      - "8000:8000"
    env_file:
      - .prod_env
    volumes:
      - "./data:/data"
    restart: on-failure
  alvokanto:
    volumes:
      - "./data:/data"
    restart: on-failure
