version: "3.1"

services:
  jughisto:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "50051"
  alvokanto:
    depends_on:
      - jughisto
    build:
      context: .
      dockerfile: alvokanto/Dockerfile
    privileged: true
  database:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --locale=C.UTF-8
      POSTGRES_USER: jughisto
      POSTGRES_DB: jughisto
